<p>Estimado(a) profesor(a) <b>{{nombre_apellidos}}</b></p>

<p>Para culminar su proceso de inscripci&oacute;n, ac&eacute;rquese a cualquier agencia autorizada del Banco de la Naci&oacute;n, en el horario de atención de sus oficinas y dentro del plazo de inscripción, portando su DNI o Carnet de Extranjer&oacute;a y el Formato Digital de Inscripción adjunto a este correo.<br />
<br />
Recuerde verificar que los datos consignados sean correctos antes de presentar este formato en el Banco.<br />
<br />
Este tr&aacute;mite es obligatorio para quedar inscrito y poder participar en el <?php echo $this->name_concurso; ?>.<br />
<br />
Le recordamos que su c&oacute;digo de validaci&oacute;n para el proceso de inscripci&oacute;n es: <strong>{{codigo_validacion}}</strong>.</p>

<p>Atentamente,<br />
Direcci&oacute;n de Evaluaci&oacute;n Docente</p>

<p style="text-align:right">&nbsp;</p>