<style>
    .lblcabecera {
        background-color: #098ca6;
        color: white;
        padding: 5px;
        -webkit-border-radius: 3px;
        -moz-border-radius: 3px;
        border-radius: 3px;
    }
    #rs_madm_lista_formatos_ins {
            display: none;
}
</style>
<div class="modal fade" id="modal_lista_ins" data-backdrop="false" name="modal_lista_ins" tabindex="-1" role="dialog" aria-labelledby="Modal lista de formatos de inscripción" >
    <div class="modal-dialog  modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="ttl_titulo_firma">Lista de formatos de inscripción</h4>
            </div>
            <div class="modal-body" style="overflow-y: scroll;height: 430px;overflow-x: hidden;">
                <table id="adm_lista_formatos_ins"></table>
                <div id="adm_lista_formatos_ins_pager"></div>
                <br>
                <table>
                    <tr><td><span class="label label-warning ">SIN CONFIRMAR</span></td><td>: Registro de inscripción sin confirmar en el Banco de la Nación.</td></tr>
                    <tr><td><span class="label label-success">CONFIRMADO</span></td><td>: Registro de inscripción confirmado en el Banco de la Nación.</td></tr>
                    <tr><td><span class="label label-danger">ANULADO</span></td><td>: Registro de inscripción anulado. </td></tr>
                </table>
            </div>
            <div class="modal-footer">
                <input type="button" class="btn boton"  id="btn_cerrar_modal_lis" name="btn_cerrar_modal_lis" value="Cerrar">
            </div>
        </div>
    </div>
</div>