<!--<div id="navbar" class="col-lg-2 col-md-2  col-sm-2 col-xs-0 navbar-collapse collapse" style="background-color: white; padding: 20px;">-->
<div id="navbar" class="col-lg-2 col-md-0  col-sm-0 col-xs-0 navbar-collapse" style="background-color: white; padding: 20px;">
   <?php
   echo $this->partial('layout/_menu.phtml', [
       'users_acl' => $this->users_acl
   ]);
   ?>


</div>
<!--<div class="col-lg-10 col-md-10  col-sm-10 col-xs-9 main" style="background-color: white; margin-bottom: 100px;">-->
<div class="col-lg-10 col-md-12 col-sm-12 col-xs-12 main" style="background-color: white; margin-bottom: 100px;">
   <div id="workArea">
   </div>
</div>