

<div id="navbar" class="col-lg-2 col-md-2  col-sm-2 col-xs-0 navbar-collapse collapse" style="background-color: white; padding: 20px;">
    <?php
//var_dump($this->users_acl);
    echo $this->partial('layout/_menu.phtml', [
        'users_acl' => $this->users_acl
    ]);
    ?>


</div>
<div class="col-lg-9 col-md-9  col-sm-9 col-xs-9 main" style="background-color: white;">
    <div id="workArea">
    </div>
</div>
