<?php echo $this->doctype(); ?>

<html lang="en">


    <?php
    // Header
    echo $this->partial('_header.phtml', []);
    ?>   


    <body>
        <h1>LAYOUT ADMIN</h1>
        <?php
        echo $this->partial('_navbar.phtml', []);
        ?> 
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <?php
            echo $this->partial('_menu.phtml', []);
            ?>
            <?php
            // Footer
            echo $this->partial('_footer.phtml', []);
            ?>  

        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
