<?php
echo $this->doctype();
$base_url = $this->basePath();
$apps_var = $this->apps_var;
//var_dump($apps_var);
$usuario = $this->users_acl->rows;
//$usuario = $usuario->rows;
//var_dump($usuario);
$recuperar_config = $this->recuperar_config;
?>

<html lang="en">


    <head>
        <meta charset="utf-8">

        <?php echo $this->headTitle($apps_var['app_title'])->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>
        <script type="text/javascript">
            var root = "<?php echo $base_url; ?>";

            var min_clave = <?php echo $recuperar_config['caracteres_min_clave']; ?>;
            var max_clave = <?php echo $recuperar_config['caracteres_max_clave']; ?>;
            var min_dni = <?php echo $recuperar_config['caracteres_min_dni']; ?>;
            var max_dni = <?php echo $recuperar_config['caracteres_max_dni']; ?>;
            var max_correo = <?php echo $recuperar_config['caracteres_max_correo']; ?>;

        </script>
        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/app/menu_datos_usuario.js?v=' . md5(time())))
                ->prependFile($this->basePath('js/app/menu_presentacion.js?v=' . md5(time())))
                ->prependFile($this->basePath('js/app/menu.js?v=' . md5(time())))
                ->prependFile($this->basePath('js/app/app.js?v=' . md5(time())))
                ->prependFile($this->basePath('js/app/_strings.js'))
                ->prependFile($this->basePath('js/lib/bootbox.min.js'))
                ->prependFile($this->basePath('js/lib/kakashi.js'))
                ->prependFile($this->basePath('js/lib/naruto.js'))
                ->prependFile($this->basePath('js/lib/BaseXJS/jquery.filter_input.js'))
                ->prependFile($this->basePath('js/lib/BaseXJS/jquery.commons.js'))
                ->prependFile($this->basePath('js/lib/BaseXJS/BaseX.js'))
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>


    </head>


    <body>

        <nav class="navbar navbar-inverse banner_top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
            </div>
        </nav>
        <div class="row row-fluid">
            <div class="col-md-12 banner_top_titulo">
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <a class="text-center" href="http://evaluaciondocente.perueduca.pe" target="_blank">
                        <img class=" img-responsive center-block " style="max-height: 80px;" src="<?php echo $base_url; ?>/img/logo-sistema.png">
                    </a>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <a class="text-center" href="http://www.minedu.gob.pe/" target="_blank">
                        <img class="img-responsive center-block" src="<?php echo $base_url; ?>/img/logo_ministerio_educacion.gif">
                    </a>
                </div>
            </div>
        </div>
        <div class="row dashboard_barra_top">

            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 text-center">
                Bienvenido(a): <?php echo $usuario->first_name . ' ' . $usuario->last_name; ?>
                <div>
                    Último acceso: <?php
                    if (utf8_encode($usuario->fec_ultimo_acceso) === '') {
                        echo date("Y-m-d H:i:s");
                    } else {
                        echo $usuario->fec_ultimo_acceso;
                    };
                    ?>
                    <input type="hidden" id="hdn_sesion_token" name="hdn_sesion_token" value="<?php echo $this->token_sesion; ?>" />
                </div>
            </div>
<!--            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12  text-center">
                Último acceso: <?php
                if (utf8_encode($usuario->fec_ultimo_acceso) === '') {
                    echo date("Y-m-d H:i:s");
                } else {
                    echo $usuario->fec_ultimo_acceso;
                };
                ?>

                <input type="hidden" id="hdn_sesion_token" name="hdn_sesion_token" value="<?php echo $this->token_sesion; ?>" />
            </div>-->
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12  text-center">
                <?php echo utf8_encode($usuario->dias_restantes); ?>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 text-center">
                <a id="btn_cerrar_sesion" href="<?php echo $this->url('usuario/sec', array('action' => 'logout')); ?>">Cerrar sesión</a>
            </div>
        </div>
        <!--        <nav class="navbar navbar-inverse banner_top">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                    </div>

                </nav>-->
        <div class="container-fluid">

            <?php
//            echo $this->partial('_menu.phtml', []);
            ?>
            <?php echo $this->content; ?>
            <hr>



            <footer class="footer">
                <div class="container">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 text-center">
                        <br />
                        <p class="text-muted footer_color">
                            Línea de atención al comité de evaluación<br />
                            <?php echo $apps_var['number_support1']; ?><br>
                        </p>
                        <!--<a href="mailto:evaluaciondocente.cpm@perueduca.pe">evaluaciondocente.cpm@perueduca.pe</a>-->
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 text-center">
                        <br />
                        <p class="text-muted footer_color">
                            <?php echo date('Y'); ?> &copy; Todos los derechos reservados
                        </p>
                    </div>
                    <!--<div class="clearfix"></div>-->
                </div>
            </footer>

        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
