<style>
    .ui-jqgrid .ui-jqgrid-btable tbody tr.jqgrow td {
        white-space: normal !important;
        padding: 10px;
    }

    .ui-jqgrid .ui-jqgrid-htable .ui-th-div {
        height: 40px;
        margin-top: 5px;
        padding: 10px;
        display: list-item;
        background-color: #CAE7EA;
    }
    .ui-state-hover {
        border : 1px solid #CAE7EA;
        background: #14A3BD;
    }

    .ui-th-ltr, .ui-jqgrid .ui-jqgrid-htable th.ui-th-ltr {
        background-color: #CAE7EA;
    }

</style>
<div class="row">
    <div>
        <ol class="breadcrumb">
            <li><a href="#">Inicio</a></li>
            <li class="active">Instrumentos</li>
        </ol>
    </div>    
</div>
<div class="row">
    <div class="tab-pane fade active in" id="responsable">
        <div class="tab-titulo">Consulta de instrumentos</div>

        <fieldset class="campo">
            <div class="form-group">
                <div class="col-md-6">
                    <label for="txtnombre" class="col-xs-3 col-sm-3 col-md-4 control-label">Estrategia</label>
                    <div class="col-xs-6 col-sm-7 col-md-7 colxs2">
                        <select name="txtfono" id="" class="form-control" style="margin-left: 15px;">
                            <option value="0">--Seleccione--</option>
                            <option value="1">01 - Estrategia</option>
                            <option value="2">02 - Estrategia</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-6">
                    <label for="txtnombre" class="col-xs-3 col-sm-3 col-md-4 control-label">Intervención</label>
                    <div class="col-xs-6 col-sm-7 col-md-7 colxs2">
                        <select name="txtfono" id="" class="form-control" style="margin-left: 15px;">
                            <option value="0">--Seleccione--</option>
                            <option value="1">01 - Intervención</option>
                            <option value="2">02 - Intervención</option>
                        </select>
                    </div>
                </div>
            </div>
            <br>
            <br>
            <div class="form-group">
                <div class="col-md-6">
                    <label for="txtnombre" class="col-xs-3 col-sm-3 col-md-4 control-label">DRE:</label>
                    <div class="col-xs-6 col-sm-7 col-md-7 colxs2">
                        <select name="txtfono" id="" class="form-control" style="margin-left: 15px;">
                            <option value="0">--Seleccione--</option>
                            <option value="1">01 - Dre</option>
                            <option value="2">02 - Dre</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-6">
                    <label for="txtnombre" class="col-xs-3 col-sm-3 col-md-4 control-label">UGEL:</label>
                    <div class="col-xs-6 col-sm-7 col-md-7 colxs2">
                        <select name="txtfono" id="" class="form-control" style="margin-left: 15px;">
                            <option value="0">--Seleccione--</option>
                            <option value="1">01 - Ugel</option>
                            <option value="2">02 - Ugel</option>
                        </select>
                    </div>
                </div>
            </div>
            <br>
            <br>
            <div class="form-group">
                <label for="txttipoges" class="col-xs-3 col-sm-3 col-md-4 control-label">Institucion educativa</label>
                <div class="col-xs-6 col-sm-7 col-md-7 colxs2">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search" name="srch-term" id="srch-term">
                        <div class="input-group-btn">
                            <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            <br>
            <div class="form-group pull-right botones group-one-resp">
                <button type="button" class="btn btn-ttc btn-editarinfo"> Buscar&nbsp;&nbsp;<i class="glyphicon glyphicon-search"></i></button>
                <button type="button" class="btn btn-tts btn-editarinfo"> Limpiar&nbsp;&nbsp;<i class="glyphicon glyphicon-erase"></i></button>
            </div>        

        </fieldset>    
    </div>
</div>
<div  class="row">
    <div class="col-md-6">
        <label>Resultados de búsqueda</label>

    </div>
</div>
<div  class="row">
    <div class="col-md-6">
        <table id="grid_instrumentos"></table>
        <div id="pager_grid_instrumentos"></div>
    </div>
</div>
<br>
<br>
<div  class="row">
    <div class="col-md-6">
        <label>Informantes por instrumento</label>

    </div>
</div>
<div  class="row">
    <div class="col-md-6">
        <table id="grid_instrumentos_detail"></table>
        <div id="pager_grid_instrumentos_detail"></div>
    </div>
</div>
